version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  build:
        working_directory: ~/repo
        docker:
            - image: circleci/node:8.10
        steps:
            - checkout
            - attach_workspace:
                # Must be absolute path or relative path from working_directory
                at: ~/repo
            - restore_cache: # special step to restore the dependency cache
                key: dependency-cache-{{ checksum "package.json" }}
            - run: yarn install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
                    - yarn.lock
            - run: yarn build:staging
            - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
                # taken to be the root directory of the workspace.
                root: ~/repo
                paths:
                    - build
    deploy-eb:
        working_directory: ~/repo
        docker:
            - image: circleci/python:2.7-jessie
        steps:
            - attach_workspace:
                # Must be absolute path or relative path from working_directory
                at: ~/repo
            - run:
                name: Install awscli
                command: sudo pip install awsebcli
            - run: eb deploy pop-production-staging
  deploy-staging:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install nasm python-dev libpng-dev python-pip build-essential libpython-dev
            pip install awsebcli --upgrade --user
      - run: 
          name: Build
          command: yarn && yarn build:staging
      - run:
          name: AWS credentials
          command: |
            mkdir ~/.aws
            echo "[eb-cli]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
      - run:
          name: Deploy
          command: ~/.local/bin/eb deploy pop-production-staging
workflows:
  version: 2
  test-then-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-eb:
          requires:
            - build
          filters:
            branches:
              only: master
      # - deploy-staging:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master
